INSERT INTO huff_post (name) VALUES 
	("BEASTS OF NO NATION"),
	("BEEBA BOYS"),
	("BLACK MASS"),
	("BROOKLYN"),
	("THE DANISH GIRL"),
	("DEMOLITION"),
	("THE DRESSMAKER"),
	("EYE IN THE SKY"),
	("FORSAKEN"),
	("FREEHELD"),
	("HYENA ROAD"),
	("I SMILE BACK"),
	("LEGEND"),
	("THE LOBSTER"),
	("LOLO"),
	("THE MAN WHO KNEW INFINITY"),
	("THE MARTIAN"),
	("THE PROGRAM"),
	("REMEMBER"),
	("SEPTEMBERS OF SHIRAZ"),
	("SPOTLIGHT"),
	("STONEWALL"),
	("COLONIA"),
	("DESIERTO"),
	("FAMILIES"),
	("THE FAMILY FANG"),
	("GUILTY"),
	("THE IDOL"),
	("THE LADY IN THE VAN"),
	("MAGGIE'S PLAN"),
	("PARCHED"),
	("ROOM"),
	("SUNSET SONG"),
	("TRUMBO"),
	("WHERE TO INVADE NEXT"),
	("YOUTH");

INSERT INTO national_post (name) VALUES 
	("THE TREASURE"),
	("DHEEPAN"),
	("SPOTLIGHT"),
	("SLEEPING GIANT"),
	("45 YEARS"),
	("THE MARTIAN"),
	("MISSISSIPPI GRIND"),
	("FRANCOFONIA"),
	("EVERY THING WILL BE FINE"),
	("LAND OF MINE"),
	("SICARIO");









